# Dockerfile for Vite Dev Server
FROM node:24-bullseye-slim


RUN apt-get update -qq && apt-get install -y git

WORKDIR /app

COPY package.json package.lock ./
RUN npm ci

# TODO: cache dependencies

COPY . .

# TODO: clean up and only copy the necessary frontend files

EXPOSE 3035

