services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      # Mount the DB dumps folder into the container, to be able to create & access database dumps:
      - ./db/dumps:/db/dumps
      # Mount out tmp folder, we might want to have access to something there during development:
      - ./tmp:/tmp
      # Mount our 'restoredb' script:
      - ./bin/restoredb:/bin/restoredb:ro
      # Mount our 'dumpdb' script:
      - ./bin/dumpdb:/bin/dumpdb:ro
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - backend-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_RAILS_USER:-rails}
      POSTGRES_PASSWORD: ${POSTGRES_RAILS_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_RAILS_DB:-app}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_RAILS_USER:-rails} -d ${POSTGRES_RAILS_DB:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8-alpine
    command: "redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru"
    ports:
      - "6379:6379"
    volumes:
      - backend-redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rails:
    build: .
    depends_on:
      - frontend
      - db
      - redis
    entrypoint: ./docker-rails.sh
    env_file: ".env"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: ${POSTGRES_RAILS_USER:-rails}
      POSTGRES_PASSWORD: ${POSTGRES_RAILS_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_RAILS_DB:-app}
      RAILS_ENV: development
      WAIT_HOSTS: db:5432
      DATABASE_URL: postgresql://rails:password@db
      VITE_RUBY_AUTO_BUILD: "false"
      VITE_RUBY_HOST: frontend
      VITE_RUBY_PORT: 3036
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    entrypoint: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
      VITE_RUBY_ROOT: /app
    volumes:
      - .:/app
    ports:
      - "3036:3036"

volumes:
  backend-redis-data:
  backend-postgres-data:
  backend-rubygems:

